[env]
_.path = ['./target/debug/']

[tools]
"github:axodotdev/cargo-dist" = "0.30.3"
"cargo:cargo-release" = "0.25.22"
"ubi:casey/just" = "1.46.0"
"aqua:mvdan/sh" = "3.12.0"
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:google/yamlfmt" = "0.21.0"
"aqua:rhysd/actionlint" = "1.7.10"
"npm:markdownlint-cli2" = "0.20.0"
